defaults:
  - _self_
  - vision: siglip
  - training: flamingo_alignment
  - flamingo: softwhere

llm: global
resume: null

wandb:
  project: tayavision-flamingo-softwhere
  entity: null
  mode: online
